<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SmartDonationSystem.Core\SmartDonationSystem.Core.csproj" />
    <ProjectReference Include="..\SmartDonationSystem.DataAccess\SmartDonationSystem.DataAccess.csproj" />
    <ProjectReference Include="..\SmartDonationSystem.Shared\SmartDonationSystem.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CloudinaryDotNet" Version="1.27.9" />
    <PackageReference Include="Hangfire" Version="1.8.23" />
    <PackageReference Include="Hangfire.SqlServer" Version="1.8.23" />
    <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.3.1" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Modules\Cloud\" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="C:\Users\MICHEAL\.nuget\packages\tesseract\5.2.0\build\\..\x64\leptonica-1.82.0.dll" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="C:\Users\MICHEAL\.nuget\packages\tesseract\5.2.0\build\\..\x64\tesseract50.dll" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="C:\Users\MICHEAL\.nuget\packages\tesseract\5.2.0\build\\..\x64\leptonica-1.82.0.dll" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="C:\Users\MICHEAL\.nuget\packages\tesseract\5.2.0\build\\..\x64\tesseract50.dll" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="C:\Users\MICHEAL\.nuget\packages\tesseract\5.2.0\build\\..\x86\leptonica-1.82.0.dll" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="C:\Users\MICHEAL\.nuget\packages\tesseract\5.2.0\build\\..\x86\tesseract50.dll" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="C:\Users\MICHEAL\.nuget\packages\tesseract\5.2.0\build\\..\x64\leptonica-1.82.0.dll" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="C:\Users\MICHEAL\.nuget\packages\tesseract\5.2.0\build\\..\x64\tesseract50.dll" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="C:\Users\MICHEAL\.nuget\packages\tesseract\5.2.0\build\\..\x86\leptonica-1.82.0.dll" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="C:\Users\MICHEAL\.nuget\packages\tesseract\5.2.0\build\\..\x86\tesseract50.dll" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="C:\Users\MICHEAL\.nuget\packages\tesseract\5.2.0\build\\..\x64\leptonica-1.82.0.dll" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="C:\Users\MICHEAL\.nuget\packages\tesseract\5.2.0\build\\..\x64\leptonica-1.82.0.dll" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="C:\Users\MICHEAL\.nuget\packages\tesseract\5.2.0\build\\..\x64\leptonica-1.82.0.dll" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="C:\Users\MICHEAL\.nuget\packages\tesseract\5.2.0\build\\..\x64\tesseract50.dll" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="C:\Users\MICHEAL\.nuget\packages\tesseract\5.2.0\build\\..\x86\leptonica-1.82.0.dll" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="C:\Users\MICHEAL\.nuget\packages\tesseract\5.2.0\build\\..\x86\tesseract50.dll" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="C:\Users\MICHEAL\.nuget\packages\tesseract\5.2.0\build\\..\x64\leptonica-1.82.0.dll" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="C:\Users\MICHEAL\.nuget\packages\tesseract\5.2.0\build\\..\x64\tesseract50.dll" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="C:\Users\MICHEAL\.nuget\packages\tesseract\5.2.0\build\\..\x86\leptonica-1.82.0.dll" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="C:\Users\MICHEAL\.nuget\packages\tesseract\5.2.0\build\\..\x86\tesseract50.dll" />
  </ItemGroup>

</Project>
